### ISSUE TITLE
Error creating connection to peer address

### ISSUE THREAD

**Issue by raderio** [IBM-Blockchain-Archive/fabric-images#25]
When I run "docker-compose -f four-peer-ca.yaml up"
In logs I can see

> Error handling message: Peer FSM failed while handling message (DISC_HELLO)

> vp0_1         | 12:52:00.429 [peer] chatWithPeer -> ERRO 6e3 Error creating connection to peer address 172.20.0.7:7051: grpc: timed out when dialing
> vp2_1         | 2017/03/04 12:52:00 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.20.0.3:7051: getsockopt: connection refused"; Reconnecting to {"172.20.0.3:7051" <nil>}
> vp3_1         | 2017/03/04 12:52:00 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.20.0.3:7051: getsockopt: connection refused"; Reconnecting to {"172.20.0.3:7051" <nil>}
> vp3_1         | 2017/03/04 12:52:01 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.20.0.7:7051: getsockopt: no route to host"; Reconnecting to {"172.20.0.7:7051" <nil>}
> vp3_1         | 12:52:01.126 [peer] chatWithPeer -> ERRO 73b Error creating connection to peer address 172.20.0.3:7051: grpc: timed out when dialing
> vp3_1         | 2017/03/04 12:52:01 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.20.0.3:7051: getsockopt: connection refused"; Reconnecting to {"172.20.0.3:7051" <nil>}
> vp3_1         | 12:52:01.127 [peer] chatWithPeer -> ERRO 73c Error creating connection to peer address 172.20.0.7:7051: grpc: timed out when dialing
> vp2_1         | 12:52:01.301 [peer] chatWithPeer -> ERRO 6e7 Error creating connection to peer address 172.20.0.3:7051: grpc: timed out when dialing

**Comment by mastersingh24** [comment]
what OS are you running?

**Comment by raderio** [comment]
Ubuntu 16.04

**Comment by saan099** [comment]
Same error, The containers were running perfectly yesterday. Today its throwing this error without me changing any images or committing. Something similar is happening with hyperledger-fabric images.
I'm also running Ubuntu 16.04.

**Comment by vivianLL** [comment]
Same error....Is there any way to fix it?

**Comment by mrshah-at-ibm** [comment]
This project is no longer under development. please look at https://ibm-blockchain.github.io for new fabric deployment instructions.
